import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile, lstat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createRepositoryExecution, ENVIRONMENT_EXECUTION_ROUTES_PROTOCOL } from '../src/app/repository-execution.js';
import { REPOSITORY_EXECUTION_REQUEST_PROTOCOL } from '../src/runtime/repository-execution.js';

async function command(program,args,{cwd,input=null,env=process.env}={}){return new Promise((resolve,reject)=>{const child=spawn(program,args,{cwd,env,shell:false,stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.once('error',reject);child.once('exit',(code,signal)=>resolve({exitCode:code,signal,stdout,stderr}));if(input==null)child.stdin.end();else child.stdin.end(input);});}
async function initGit(root){await command('git',['init','-q'],{cwd:root});await command('git',['config','user.name','Host'],{cwd:root});await command('git',['config','user.email','host@localhost'],{cwd:root});await command('git',['add','-A'],{cwd:root});await command('git',['commit','-q','-m','base'],{cwd:root});}
async function visible(root){const r=await command('git',['ls-files','-co','--exclude-standard','-z'],{cwd:root});assert.equal(r.exitCode,0,r.stderr);return r.stdout.split('\0').filter(Boolean);}

function localChannel(root){const classes={};for(const name of ['input','work','output','cache','scratch'])classes[name]=path.join(root,name);const ensure=async()=>{for(const dir of Object.values(classes))await mkdir(dir,{recursive:true});};const locate=async(location,{forInput=false}={})=>{await ensure();const candidate=path.join(classes[location.class],...location.path.split('/').filter(x=>x!=='.'));if(!forInput)await mkdir(path.dirname(candidate),{recursive:true});return candidate;};return {
 async health(){await ensure();return{ready:true,version:'1.0.0',features:['health','execute','observe','cancel','put','get'],reason:null};},
 async put(_target,source,destination,{maxBytes=32*1024*1024}={}){const file=await locate(destination);let offset=0;const chunks=[];while(true){const part=await source.read({offset,limit:Math.min(16*1024,maxBytes-offset)});const data=Buffer.from(part.data);chunks.push(data);offset+=data.length;if(part.eof)break;if(offset>=maxBytes)throw new Error('put limit');}await writeFile(file,Buffer.concat(chunks));return{bytes:offset,digest:'x'};},
 async get(_target,source,sink,{maxBytes=32*1024*1024}={}){const file=await locate(source,{forInput:true});const data=await readFile(file);if(data.length>maxBytes)throw new Error('get limit');await sink.write({offset:0,data,eof:true,digest:'x'});return{bytes:data.length,digest:'x'};},
 async execute(_target,operation,{signal=null,onActivity=null}={}){await ensure();const args=[];for(const arg of operation.arguments){if(typeof arg==='string')args.push(arg);else args.push(await locate(arg,{forInput:arg.class==='input'}));}const cwd=operation.directory.path==='.'?classes[operation.directory.class]:await locate(operation.directory);onActivity?.({state:'running'});if(signal?.aborted)return{completion:'observed',result:{exitCode:null,signal:null,timedOut:false,aborted:true,outputTruncated:false,stdout:'',stderr:'',startedAt:null,finishedAt:null,lastOutputAt:null}};const startedAt=new Date().toISOString();const r=await command(operation.program,args,{cwd,input:operation.input,env:{...process.env,...operation.environment}});return{completion:'observed',result:{exitCode:r.exitCode,signal:r.signal,timedOut:false,aborted:false,outputTruncated:false,stdout:r.stdout,stderr:r.stderr,startedAt,finishedAt:new Date().toISOString(),lastOutputAt:r.stdout||r.stderr?new Date().toISOString():null}};}
};}

function request(args){return{protocol:REPOSITORY_EXECUTION_REQUEST_PROTOCOL,operation:'test.operation',scope:{repository:'owner/repo',repositoryId:'123',runId:'run-1'},invocation:{tool:'node',arguments:args,workingDirectory:'.'},environment:{CI:'1'},transfers:[],limits:{timeoutMs:120000,maxOutputBytes:1024*1024},stdin:null,signal:null,onActivity:null};}

test('production composition round-trips candidate bytes and preserves ignored guest state across source resync',async()=>{const temp=await mkdtemp(path.join(os.tmpdir(),'db-stage6-app-'));const host=path.join(temp,'host');const guest=path.join(temp,'guest');try{await mkdir(host);await writeFile(path.join(host,'.gitignore'),'build/\n');await writeFile(path.join(host,'a.txt'),'alpha\n');await initGit(host);const entry={record:{identity:'env-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',subject:'123',profile:'linux-dev'},observation:{exists:true,owned:true,compatible:true,state:'running'}};const fakeState={inspect:async()=>({ready:true,identity:'f'.repeat(32),reason:null}),listEnvironments:async()=>[entry],observeEnvironment:async()=>entry};const channel=localChannel(guest);const routes={protocol:ENVIRONMENT_EXECUTION_ROUTES_PROTOCOL,routes:[{subject:'123',profile:'linux-dev',preferred:true,access:{family:'linux'}}]};const execution=await createRepositoryExecution({stateDirectory:path.join(temp,'state'),platform:'linux',routes,rootFor:async()=>host,listPaths:async(root)=>visible(root),resolveSubject:async(scope)=>scope.repositoryId,resolveTool:async(tool)=>({program:tool,arguments:[]}),createState:async()=>fakeState,createPreparation:async()=>({ensure:async()=>({generation:'b'.repeat(64)}),connection:async()=>({family:'linux'})}),createChannel:async()=>channel});assert.equal(execution.inspect().ready,true);
 const first=await execution.execute(request(['-e',`const fs=require('node:fs');fs.mkdirSync('build',{recursive:true});fs.writeFileSync('build/cache','persist');fs.writeFileSync('a.txt','changed\\n');fs.writeFileSync('new.txt','new\\n');console.log('first')`]));assert.equal(first.exitCode,0);assert.match(first.evidence.identity,/^execution-/u);assert.equal(await readFile(path.join(host,'a.txt'),'utf8'),'changed\n');assert.equal(await readFile(path.join(host,'new.txt'),'utf8'),'new\n');await assert.rejects(readFile(path.join(host,'build','cache')),{code:'ENOENT'});
 await writeFile(path.join(host,'a.txt'),'host-next\n');const second=await execution.execute(request(['-e',`const fs=require('node:fs');process.stdout.write(fs.readFileSync('build/cache','utf8')+'|'+fs.readFileSync('a.txt','utf8'))`]));assert.equal(second.stdout,'persist|host-next\n');assert.equal(await readFile(path.join(guest,'work','build','cache'),'utf8'),'persist');
 }finally{await rm(temp,{recursive:true,force:true});}});

test('authoritative source drift during guest execution rejects candidate import',async()=>{const temp=await mkdtemp(path.join(os.tmpdir(),'db-stage6-drift-'));const host=path.join(temp,'host');const guest=path.join(temp,'guest');try{await mkdir(host);await writeFile(path.join(host,'a.txt'),'alpha\n');await initGit(host);const entry={record:{identity:'env-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',subject:'123',profile:'linux-dev'},observation:{exists:true,owned:true,compatible:true,state:'running'}};const fakeState={inspect:async()=>({ready:true,identity:'e'.repeat(32),reason:null}),listEnvironments:async()=>[entry],observeEnvironment:async()=>entry};const base=localChannel(guest);const channel={...base,async execute(target,operation,options){const result=await base.execute(target,operation,options);const hasRun=operation.arguments.some((arg)=>arg==='run');if(hasRun&&operation.arguments.some((arg)=>typeof arg==='object'&&arg.class==='input'&&arg.path.startsWith('control/operation-')))await writeFile(path.join(host,'a.txt'),'external-drift\n');return result;}};const execution=await createRepositoryExecution({stateDirectory:path.join(temp,'state'),platform:'linux',routes:{protocol:ENVIRONMENT_EXECUTION_ROUTES_PROTOCOL,routes:[{subject:'123',profile:'linux-dev',access:{family:'linux'}}]},rootFor:async()=>host,listPaths:async(root)=>visible(root),resolveSubject:async()=> '123',resolveTool:async(tool)=>({program:tool,arguments:[]}),createState:async()=>fakeState,createPreparation:async()=>({ensure:async()=>({generation:'c'.repeat(64)}),connection:async()=>({family:'linux'})}),createChannel:async()=>channel});await assert.rejects(()=>execution.execute(request(['-e',`require('node:fs').writeFileSync('a.txt','guest-change\\n')`])),/authoritative source changed during repository execution|stale/u);assert.equal(await readFile(path.join(host,'a.txt'),'utf8'),'external-drift\n');}finally{await rm(temp,{recursive:true,force:true});}});
