import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readlink, rm, writeFile, symlink } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path'; import { createHash } from 'node:crypto';
import { FILE_TREE_DELTA_PROTOCOL, FILE_TREE_VERSION, snapshotFileTree, stageFileTreeDelta, applyStagedFileTreeDelta } from '../src/runtime/file-tree-transfer.js';
function stableJson(value){if(Array.isArray(value))return `[${value.map(stableJson).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stableJson(value[k])}`).join(',')}}`;return JSON.stringify(value);} function digest(v){return createHash('sha256').update(Buffer.from(stableJson(v))).digest('hex');} function bytesDigest(b){return createHash('sha256').update(b).digest('hex');}

test('snapshot is content addressed and supports internal symlinks', async(t)=>{ const root=await mkdtemp(path.join(os.tmpdir(),'db-tree-')); try{await mkdir(path.join(root,'src')); await writeFile(path.join(root,'src','a.txt'),'alpha'); try { await symlink('a.txt',path.join(root,'src','link')); } catch (error) { if (process.platform === 'win32' && error?.code === 'EPERM') { t.skip('symlink creation is not permitted by this Windows host'); return; } throw error; } const snap=await snapshotFileTree({root,listPaths:async()=>['src/a.txt','src/link']}); assert.equal(snap.manifest.entries.length,2); assert.match(snap.manifest.digest,/^[a-f0-9]{64}$/u); assert.equal(snap.manifest.entries[1].type,'symlink');} finally{await rm(root,{recursive:true,force:true});}});

test('candidate bytes stage before atomic apply and traversal is rejected',async()=>{ const root=await mkdtemp(path.join(os.tmpdir(),'db-tree-root-')); const staging=await mkdtemp(path.join(os.tmpdir(),'db-tree-stage-')); try{await writeFile(path.join(root,'a.txt'),'old'); const data=Buffer.from('new'); const part={name:'part-0-0',offset:0,size:data.length,digest:bytesDigest(data)}; const body={protocol:FILE_TREE_DELTA_PROTOCOL,version:FILE_TREE_VERSION,basisDigest:'a'.repeat(64),entries:[{path:'a.txt',action:'write',size:data.length,digest:bytesDigest(data),executable:false,parts:[part]},{path:'gone.txt',action:'delete'}],totalBytes:data.length}; const manifest={...body,digest:digest(body)}; const normalized=await stageFileTreeDelta({manifest,root,stagingRoot:staging,readPart:async(name)=>{assert.equal(name,'part-0-0');return data;}}); assert.equal(await readFile(path.join(root,'a.txt'),'utf8'),'old'); await applyStagedFileTreeDelta({root,stagingRoot:staging,manifest:normalized}); assert.equal(await readFile(path.join(root,'a.txt'),'utf8'),'new'); const badBody={...body,entries:[{path:'../escape',action:'delete'}],totalBytes:0}; const bad={...badBody,digest:digest(badBody)}; await assert.rejects(()=>stageFileTreeDelta({manifest:bad,root,stagingRoot:staging,readPart:async()=>Buffer.alloc(0)}),/invalid segment|portable/u); } finally{await rm(root,{recursive:true,force:true});await rm(staging,{recursive:true,force:true});}});

test('malicious symlink target escaping root is rejected',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'db-tree-root-'));try{const body={protocol:FILE_TREE_DELTA_PROTOCOL,version:FILE_TREE_VERSION,basisDigest:'b'.repeat(64),entries:[{path:'x/link',action:'symlink',target:'../../outside'}],totalBytes:0};const manifest={...body,digest:digest(body)};await assert.rejects(()=>stageFileTreeDelta({manifest,root,stagingRoot:path.join(root,'stage'),readPart:async()=>Buffer.alloc(0)}),/escapes root/u);}finally{await rm(root,{recursive:true,force:true});}});
