import { createHash, randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { lstat, mkdir, open, readFile, readlink, realpath, rename, rm, symlink, writeFile, chmod } from 'node:fs/promises';
import path from 'node:path';

const TREE_PROTOCOL = 'devbridge/file-tree-v1';
const DELTA_PROTOCOL = 'devbridge/file-tree-delta-v1';
const TREE_VERSION = '1.1.0';
const STATE_PROTOCOL = 'devbridge/work-tree-state-v1';
const OPERATION_PROTOCOL = 'devbridge/work-operation-v1';
const DIGEST = /^[a-f0-9]{64}$/u;
const PART_NAME = /^part-[a-f0-9]{64}$/u;
const SAFE_PROGRAM = /^[A-Za-z][A-Za-z0-9_.+-]{0,159}$/u;
const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]{0,127}$/u;
const MAX_ENTRIES = 100_000;
const MAX_TREE_BYTES = 8 * 1024 * 1024 * 1024;
const PART_BYTES = 32 * 1024 * 1024;
const MAX_DESCRIPTOR_BYTES = 8 * 1024 * 1024;

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
}
function sha256(value) { return createHash('sha256').update(value).digest('hex'); }
function digestObject(value) { return sha256(Buffer.from(stableJson(value), 'utf8')); }
function requireObject(value, name) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${name} must be an object`); return value; }
function onlyKeys(value, allowed, name) { for (const key of Object.keys(value)) if (!allowed.has(key)) throw new TypeError(`${name}.${key} is not allowed`); }
function exactDigest(value, name) { const text = String(value ?? '').toLowerCase(); if (!DIGEST.test(text)) throw new TypeError(`${name} is invalid`); return text; }
function isWithin(root, candidate) { const relative = path.relative(path.resolve(root), path.resolve(candidate)); return relative === '' || (!path.isAbsolute(relative) && relative !== '..' && !relative.startsWith(`..${path.sep}`)); }
function normalizePath(value, name='path') { if(typeof value!=='string'||value.length===0||value.includes('\0')||Buffer.byteLength(value,'utf8')>4096)throw new TypeError(`${name} is invalid`); const portable=value.replace(/\\/gu,'/'); if(portable.startsWith('/')||portable.startsWith('//')||/^[A-Za-z]:/u.test(portable)||portable.includes(':'))throw new TypeError(`${name} must be portable and relative`); const parts=portable.split('/'); if(parts.some((part)=>part===''||part==='.'||part==='..'))throw new TypeError(`${name} contains an invalid segment`); return parts.join('/'); }
function normalizeTarget(value, entryPath, root) { if(typeof value!=='string'||value.length===0||value.includes('\0')||Buffer.byteLength(value,'utf8')>4096||path.isAbsolute(value))throw new TypeError(`symlink target is invalid for ${entryPath}`); const parent=path.dirname(path.join(root,...entryPath.split('/'))); if(!isWithin(root,path.resolve(parent,value)))throw new TypeError(`symlink target escapes root for ${entryPath}`); return value; }

async function workRoot() { const root=await realpath(process.cwd()); const info=await lstat(root); if(!info.isDirectory()||info.isSymbolicLink())throw new Error('work root must be a real directory'); return root; }
async function safeParent(root, relative) { let current=root; const parts=relative.split('/'); for(const segment of parts.slice(0,-1)){ const next=path.join(current,segment); try{const info=await lstat(next); if(!info.isDirectory()||info.isSymbolicLink())throw new Error(`work path parent is unsafe: ${relative}`);}catch(error){if(error?.code!=='ENOENT')throw error;await mkdir(next,{mode:0o700});} current=await realpath(next); if(!isWithin(root,current))throw new Error(`work path escaped root: ${relative}`);} return path.join(root,...parts); }

function baseEnvironment() { const names=process.platform==='win32'?['PATH','Path','PATHEXT','SystemRoot','SYSTEMROOT','WINDIR','TEMP','TMP','ComSpec','ProgramData','ProgramFiles','ProgramFiles(x86)']:['PATH','HOME','TMPDIR','TMP','TEMP','LANG','LC_ALL','LC_CTYPE','TZ']; const env={}; for(const name of names)if(typeof process.env[name]==='string')env[name]=process.env[name]; env.GIT_TERMINAL_PROMPT='0'; env.DEVBRIDGE_NONINTERACTIVE='1'; env.NO_COLOR??='1'; return env; }

async function runProcess(program,args,{cwd=process.cwd(),environment={},input=null,capture=true,allowFailure=false}={}) { return new Promise((resolve,reject)=>{ const child=spawn(program,args,{cwd,env:{...baseEnvironment(),...environment},shell:false,windowsHide:true,stdio:['pipe',capture?'pipe':'inherit',capture?'pipe':'inherit']}); let stdout=Buffer.alloc(0),stderr=Buffer.alloc(0); if(capture){child.stdout.on('data',(chunk)=>{stdout=Buffer.concat([stdout,chunk]);if(stdout.length>4*1024*1024)stdout=stdout.subarray(stdout.length-4*1024*1024);});child.stderr.on('data',(chunk)=>{stderr=Buffer.concat([stderr,chunk]);if(stderr.length>4*1024*1024)stderr=stderr.subarray(stderr.length-4*1024*1024);});} child.once('error',reject); child.once('exit',(code,signal)=>{const result={exitCode:code,signal,stdout:stdout.toString('utf8'),stderr:stderr.toString('utf8')}; if(!allowFailure&&code!==0)reject(new Error(`${program} failed: ${(result.stderr||result.stdout).trim().slice(0,2048)}`));else resolve(result);}); if(input==null)child.stdin.end();else child.stdin.end(input); }); }
async function git(args,{allowFailure=false}={}) { return runProcess('git',['-c','credential.helper=','-c','core.autocrlf=false','-c','core.eol=lf','-c','protocol.ext.allow=never','-c','protocol.file.allow=never',...args],{allowFailure}); }

async function readJson(file,name,maxBytes=MAX_DESCRIPTOR_BYTES){const info=await lstat(file);if(!info.isFile()||info.isSymbolicLink()||info.size>maxBytes)throw new Error(`${name} is invalid`);return JSON.parse(await readFile(file,'utf8'));}
async function atomicJson(file,value){await mkdir(path.dirname(file),{recursive:true,mode:0o700});const tmp=`${file}.${randomUUID()}.tmp`;await writeFile(tmp,`${JSON.stringify(value)}\n`,{encoding:'utf8',mode:0o600,flag:'wx'});await rename(tmp,file);}
async function readState(file){try{const value=requireObject(await readJson(file,'work state',4*1024*1024),'work state');if(value.protocol!==STATE_PROTOCOL||!DIGEST.test(String(value.digest??''))||!Array.isArray(value.paths)||typeof value.baselineCommit!=='string'||!/^[a-f0-9]{40}$/u.test(value.baselineCommit))throw new Error('work state protocol is invalid');return value;}catch(error){if(error?.code==='ENOENT')return null;throw error;}}

function normalizeTreeManifest(raw,root){ const value=requireObject(raw,'source manifest'); onlyKeys(value,new Set(['protocol','version','entries','totalBytes','digest']),'source manifest'); if(value.protocol!==TREE_PROTOCOL||value.version!==TREE_VERSION)throw new Error('source manifest protocol is unsupported'); if(!Array.isArray(value.entries)||value.entries.length>MAX_ENTRIES)throw new Error('source manifest entries are invalid'); const seen=new Set();let total=0;const entries=value.entries.map((rawEntry,index)=>{const entry=requireObject(rawEntry,`source entry[${index}]`);const relative=normalizePath(entry.path,`source entry[${index}].path`);if(seen.has(relative))throw new Error(`source manifest duplicates ${relative}`);seen.add(relative);if(entry.type==='symlink'){onlyKeys(entry,new Set(['path','type','target']),`source entry[${index}]`);return{path:relative,type:'symlink',target:normalizeTarget(entry.target,relative,root)};}if(entry.type!=='file')throw new Error('source entry type is unsupported');onlyKeys(entry,new Set(['path','type','size','digest','executable','parts']),`source entry[${index}]`);if(!Number.isSafeInteger(entry.size)||entry.size<0||typeof entry.executable!=='boolean'||!Array.isArray(entry.parts)||entry.parts.length===0)throw new Error('source file entry is invalid');total+=entry.size;if(total>MAX_TREE_BYTES)throw new Error('source manifest exceeds byte ceiling');let offset=0;const parts=entry.parts.map((part)=>{requireObject(part,'source part');const digest=exactDigest(part.digest,'source part digest');if(typeof part.name!=='string'||!PART_NAME.test(part.name)||part.name!==`part-${digest}`||!Number.isSafeInteger(part.offset)||part.offset!==offset||!Number.isSafeInteger(part.size)||part.size<0||part.size>PART_BYTES)throw new Error('source part is invalid');offset+=part.size;return{name:part.name,offset:part.offset,size:part.size,digest};});if(offset!==entry.size)throw new Error('source parts do not cover file');return{path:relative,type:'file',size:entry.size,digest:exactDigest(entry.digest,'source file digest'),executable:entry.executable,parts};});if(value.totalBytes!==total)throw new Error('source manifest totalBytes is inconsistent');const body={protocol:value.protocol,version:value.version,entries,totalBytes:total};const digest=exactDigest(value.digest,'source manifest digest');if(digestObject(body)!==digest)throw new Error('source manifest digest is inconsistent');return{...body,digest}; }

async function prepare(manifestFile,stateFile){ const root=await workRoot();const manifest=normalizeTreeManifest(await readJson(manifestFile,'source manifest',24*1024*1024),root);const state=await readState(stateFile);let gitPresent=true;try{const info=await lstat(path.join(root,'.git'));gitPresent=info.isDirectory()||info.isFile();}catch(error){if(error?.code==='ENOENT')gitPresent=false;else throw error;}if(state&&gitPresent){const reset=await git(['reset','--hard','-q',state.baselineCommit],{allowFailure:true});if(reset.exitCode!==0)throw new Error('guest baseline reset failed');const clean=await git(['clean','-fdq'],{allowFailure:true});if(clean.exitCode!==0)throw new Error('guest candidate cleanup failed');}else if(state&&!gitPresent){throw new Error('guest baseline metadata disappeared');}const missingParts=[];const missingPartNames=new Set();if(state?.digest!==manifest.digest){const sourceDir=path.dirname(manifestFile);for(const entry of manifest.entries){if(entry.type!=='file')continue;for(const part of entry.parts){if(missingPartNames.has(part.name))continue;const partPath=path.join(sourceDir,part.name);let valid=false;try{const info=await lstat(partPath);if(info.isFile()&&!info.isSymbolicLink()&&info.size===part.size)valid=sha256(await readFile(partPath))===part.digest;}catch(error){if(error?.code!=='ENOENT')throw error;}if(!valid){missingPartNames.add(part.name);missingParts.push(part.name);}}}}process.stdout.write(`${JSON.stringify({ready:true,appliedDigest:state?.digest??null,expectedDigest:manifest.digest,missingParts})}\n`);}

async function initializeGit(root){ let present=true;try{await lstat(path.join(root,'.git'));}catch(error){if(error?.code==='ENOENT')present=false;else throw error;}if(!present)await git(['init','-q']);await git(['config','user.name','DevBridge Guest']);await git(['config','user.email','guest@localhost']);await git(['config','commit.gpgSign','false']);await git(['config','credential.helper','']);await git(['config','protocol.ext.allow','never']);await git(['config','protocol.file.allow','never']);const remotes=(await git(['remote'],{allowFailure:true})).stdout.split(/\r?\n/u).map((v)=>v.trim()).filter(Boolean);for(const remote of remotes)await git(['remote','remove',remote],{allowFailure:true});}
async function addPaths(paths){for(let index=0;index<paths.length;index+=256){const batch=paths.slice(index,index+256);if(batch.length)await git(['add','-f','--',...batch]);}}

async function applySource(manifestFile,stateFile){ const root=await workRoot();const manifest=normalizeTreeManifest(await readJson(manifestFile,'source manifest',24*1024*1024),root);const previous=await readState(stateFile);const incoming=new Set(manifest.entries.map((entry)=>entry.path));for(const relative of previous?.paths??[]){if(incoming.has(relative))continue;const destination=await safeParent(root,normalizePath(relative,'prior source path'));try{const info=await lstat(destination);if(info.isDirectory()&&!info.isSymbolicLink())throw new Error(`prior source path became a directory: ${relative}`);await rm(destination,{force:false});}catch(error){if(error?.code!=='ENOENT')throw error;}}
 const sourceDir=path.dirname(manifestFile);for(const entry of manifest.entries){const destination=await safeParent(root,entry.path);let existing=null;try{existing=await lstat(destination);}catch(error){if(error?.code!=='ENOENT')throw error;}if(existing?.isDirectory()&&!existing.isSymbolicLink())throw new Error(`source path would replace a directory: ${entry.path}`);if(entry.type==='symlink'){const tmp=`${destination}.${randomUUID()}.link`;await symlink(entry.target,tmp);await rename(tmp,destination);continue;}const tmp=`${destination}.${randomUUID()}.tmp`;const handle=await open(tmp,'wx',0o600);const whole=createHash('sha256');try{for(const part of entry.parts){const partPath=path.join(sourceDir,part.name);const info=await lstat(partPath);if(!info.isFile()||info.isSymbolicLink()||info.size!==part.size)throw new Error(`source part shape changed: ${part.name}`);const bytes=await readFile(partPath);if(sha256(bytes)!==part.digest)throw new Error(`source part digest changed: ${part.name}`);await handle.write(bytes,0,bytes.length,part.offset);whole.update(bytes);}}finally{await handle.close();}if(whole.digest('hex')!==entry.digest){await rm(tmp,{force:true});throw new Error(`source file digest changed: ${entry.path}`);}await chmod(tmp,entry.executable?0o755:0o644).catch(()=>{});await rename(tmp,destination);}
 await initializeGit(root);await git(['add','-u','--','.'],{allowFailure:true});await addPaths(manifest.entries.map((entry)=>entry.path));await git(['commit','-q','--allow-empty','-m',`DevBridge source ${manifest.digest}`]);const baselineCommit=(await git(['rev-parse','HEAD'])).stdout.trim().toLowerCase();if(!/^[a-f0-9]{40}$/u.test(baselineCommit))throw new Error('guest baseline commit identity is invalid');await atomicJson(stateFile,{protocol:STATE_PROTOCOL,digest:manifest.digest,baselineCommit,paths:manifest.entries.map((entry)=>entry.path),appliedAt:new Date().toISOString()});process.stdout.write(`${JSON.stringify({ready:true,digest:manifest.digest,baselineCommit})}\n`); }

function normalizeOperation(raw){const value=requireObject(raw,'operation descriptor');onlyKeys(value,new Set(['protocol','program','arguments','environment','stdin']),'operation descriptor');if(value.protocol!==OPERATION_PROTOCOL||typeof value.program!=='string'||!SAFE_PROGRAM.test(value.program))throw new Error('operation descriptor is invalid');if(!Array.isArray(value.arguments)||value.arguments.length>256)throw new Error('operation arguments are invalid');const args=value.arguments.map((arg,index)=>{const item=requireObject(arg,`operation argument[${index}]`);if(item.kind==='literal'){onlyKeys(item,new Set(['kind','value']),`operation argument[${index}]`);if(typeof item.value!=='string'||item.value.includes('\0')||Buffer.byteLength(item.value,'utf8')>65536)throw new Error('operation literal is invalid');return item;}if(item.kind==='location'){onlyKeys(item,new Set(['kind','index']),`operation argument[${index}]`);if(!Number.isSafeInteger(item.index)||item.index<0||item.index>255)throw new Error('operation location index is invalid');return item;}throw new Error('operation argument kind is invalid');});const environment=requireObject(value.environment??{},'operation environment');if(Object.keys(environment).length>128)throw new Error('operation environment is too large');for(const [name,entry] of Object.entries(environment)){if(!ENV_NAME.test(name)||typeof entry!=='string'||entry.includes('\0')||Buffer.byteLength(entry,'utf8')>16384)throw new Error('operation environment entry is invalid');}if(value.stdin!=null&&(typeof value.stdin!=='string'||Buffer.byteLength(value.stdin,'utf8')>4*1024*1024))throw new Error('operation stdin is invalid');return{program:value.program,arguments:args,environment:{...environment},stdin:value.stdin??null};}

async function runOperation(descriptorFile, locations){const descriptor=normalizeOperation(await readJson(descriptorFile,'operation descriptor'));const args=descriptor.arguments.map((arg)=>arg.kind==='literal'?arg.value:(()=>{const value=locations[arg.index];if(typeof value!=='string'||value.length===0)throw new Error('operation location argument is missing');return value;})());const child=spawn(descriptor.program,args,{cwd:process.cwd(),env:{...baseEnvironment(),...descriptor.environment},stdio:['pipe','pipe','pipe'],shell:false,windowsHide:true,detached:false});child.stdout.pipe(process.stdout,{end:false});child.stderr.pipe(process.stderr,{end:false});if(descriptor.stdin==null)child.stdin.end();else child.stdin.end(descriptor.stdin);const result=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',(code,signal)=>resolve({code,signal}));});if(result.signal){process.stderr.write(`operation terminated by signal ${result.signal}\n`);process.exitCode=1;}else process.exitCode=result.code??1;}

function splitNul(text){return Buffer.from(text,'utf8').toString('utf8').split('\0').filter(Boolean);}
async function collect(outputDir,stateFile){const root=await workRoot();const state=await readState(stateFile);if(!state)throw new Error('candidate collection requires an applied source baseline');const verify=(await git(['cat-file','-e',`${state.baselineCommit}^{commit}`],{allowFailure:true}));if(verify.exitCode!==0)throw new Error('guest baseline commit is unavailable');const changed=splitNul((await git(['diff','--name-only','-z',state.baselineCommit,'--'])).stdout);const untracked=splitNul((await git(['ls-files','--others','--exclude-standard','-z'])).stdout);const paths=[...new Set([...changed,...untracked].map((entry)=>normalizePath(entry,'candidate path')))].sort();if(paths.length>MAX_ENTRIES)throw new Error('candidate exceeds entry ceiling');await rm(outputDir,{recursive:true,force:true});await mkdir(outputDir,{recursive:true,mode:0o700});const entries=[];const emittedParts=new Set();let totalBytes=0;for(const relative of paths){if(relative==='.git'||relative.startsWith('.git/')||relative==='.devbridge'||relative.startsWith('.devbridge/'))throw new Error(`candidate path is reserved: ${relative}`);const candidate=path.join(root,...relative.split('/'));let info;try{info=await lstat(candidate);}catch(error){if(error?.code==='ENOENT'){entries.push({path:relative,action:'delete'});continue;}throw error;}if(info.isDirectory())continue;if(info.isSymbolicLink()){entries.push({path:relative,action:'symlink',target:normalizeTarget(await readlink(candidate),relative,root)});continue;}if(!info.isFile())throw new Error(`candidate contains unsupported file type: ${relative}`);totalBytes+=info.size;if(totalBytes>MAX_TREE_BYTES)throw new Error('candidate exceeds byte ceiling');const handle=await open(candidate,'r');const whole=createHash('sha256');const parts=[];try{for(let offset=0,index=0;offset<info.size||(info.size===0&&index===0);index+=1){const length=info.size===0?0:Math.min(PART_BYTES,info.size-offset);const bytes=Buffer.allocUnsafe(length);let read=0;while(read<length){const result=await handle.read(bytes,read,length-read,offset+read);if(result.bytesRead===0)throw new Error('candidate file changed while collecting');read+=result.bytesRead;}const data=bytes.subarray(0,read);const digest=sha256(data);const name=`part-${digest}`;if(!emittedParts.has(name)){await writeFile(path.join(outputDir,name),data,{mode:0o600,flag:'wx'});emittedParts.add(name);}parts.push({name,offset,size:data.length,digest});whole.update(data);if(info.size===0)break;offset+=data.length;}}finally{await handle.close();}entries.push({path:relative,action:'write',size:info.size,digest:whole.digest('hex'),executable:(info.mode&0o111)!==0,parts});}
 const body={protocol:DELTA_PROTOCOL,version:TREE_VERSION,basisDigest:state.digest,entries,totalBytes};const manifest={...body,digest:digestObject(body)};await writeFile(path.join(outputDir,'manifest.json'),`${JSON.stringify(manifest)}\n`,{encoding:'utf8',mode:0o600,flag:'wx'});process.stdout.write(`${JSON.stringify({ready:true,digest:manifest.digest,entries:entries.length,totalBytes})}\n`);}

async function cleanupScratch(target){let info;try{info=await lstat(target);}catch(error){if(error?.code==='ENOENT'){process.stdout.write(`${JSON.stringify({verifiedAbsent:true})}\n`);return;}throw error;}if(!info.isDirectory()||info.isSymbolicLink())throw new Error('scratch cleanup target must be a real directory');await rm(target,{recursive:true,force:false});try{await lstat(target);throw new Error('scratch cleanup target is still present');}catch(error){if(error?.code!=='ENOENT')throw error;}process.stdout.write(`${JSON.stringify({verifiedAbsent:true})}\n`);}

async function main(){const [action,...args]=process.argv.slice(2);if(action==='prepare'){if(args.length!==2)throw new Error('prepare requires manifest path and state path');return prepare(args[0],args[1]);}if(action==='apply'){if(args.length!==2)throw new Error('apply requires manifest path and state path');return applySource(args[0],args[1]);}if(action==='run'){if(args.length<1)throw new Error('run requires descriptor path');return runOperation(args[0],args.slice(1));}if(action==='collect'){if(args.length!==2)throw new Error('collect requires output path and state path');return collect(args[0],args[1]);}if(action==='cleanup-scratch'){if(args.length!==1)throw new Error('cleanup-scratch requires one target path');return cleanupScratch(args[0]);}throw new Error('workspace action is unsupported');}
main().catch((error)=>{process.stderr.write(`${error.name}: ${error.message}\n`);process.exitCode=1;});
